import type { Metadata } from "next";
import { Roboto_Flex
 } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const bitcoin = Roboto_Flex
 ({
  variable: "--font-bitcoin",
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bitcoin.variable} antialiased`}
      >
        <Navbar/>
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
